// CodeMirror, copyright (c) by Marijn Haverbeke and others
// Distributed under an MIT license: http://codemirror.net/LICENSE

(function(mod) {
  if (typeof exports == "object" && typeof module == "object") // CommonJS
    mod(require("../../lib/codemirror"));
  else if (typeof define == "function" && define.amd) // AMD
    define(["../../lib/codemirror"], mod);
  else // Plain browser env
    mod(CodeMirror);
})(function(CodeMirror) {
  "use strict";


  CodeMirror.registerHelper("hint", "irule", function(editor, options) {
    var list = [ 'ACCESS_SESSION_STARTED', 'ACCESS_SESSION_CLOSED', 'ACCESS_ACL_ALLOWED',
    'ACCESS_ACL_DENIED', 'ACCESS_POLICY_AGENT_EVENT', 'ACCESS_POLICY_COMPLETED',
    'ADAPT_REQUEST_RESULT', 'ADAPT_RESPONSE_RESULT', 'ASM_REQUEST_BLOCKING', 'ASM_REQUEST_DONE',
    'ASM_REQUEST_VIOLATION', 'ASM_RESPONSE_VIOLATION', 'AUTH_ERROR', 'AUTH_FAILURE', 'AUTH_RESULT',
    'AUTH_SUCCESS', 'AUTH_WANTCREDENTIAL', 'CACHE_REQUEST', 'CACHE_RESPONSE', 'CACHE_UPDATE',
    'CATEGORY_MATCHED', 'CLASSIFICATION_DETECTED', 'CLIENT_ACCEPTED', 'CLIENT_CLOSED', 'CLIENT_DATA',
    'CLIENT_LINE', 'CLIENTSSL_CLIENTCERT', 'CLIENTSSL_CLIENTHELLO', 'CLIENTSSL_DATA', 'CLIENTSSL_HANDSHAKE',
    'CLIENTSSL_SERVERHELLO_SEND', 'DIAMETER_INGRESS', 'DIAMETER_EGRESS', 'DNS_REQUEST', 'DNS_RESPONSE',
    'FIX_MESSAGE', 'FLOW_INIT', 'HTML_COMMENT_MATCHED', 'HTML_TAG_MATCHED', 'HTTP_CLASS_FAILED',
    'HTTP_CLASS_SELECTED', 'HTTP_DISABLED', 'HTTP_PROXY_REQUEST', 'HTTP_REQUEST', 'HTTP_REQUEST_DATA',
    'HTTP_REQUEST_SEND', 'HTTP_RESPONSE', 'HTTP_RESPONSE_CONTINUE', 'HTTP_RESPONSE_DATA', 'HTTP_REQUEST_RELEASE',
    'HTTP_RESPONSE_RELEASE', 'ICAP_REQUEST', 'ICAP_RESPONSE', 'IN_DOSL7_ATTACK', 'LB_FAILED',
    'LB_QUEUED', 'LB_SELECTED', 'NAME_RESOLVED', 'PCP_REQUEST', 'PCP_RESPONSE', 'QOE_PARSE_DONE',
    'REWRITE_REQUEST_DONE', 'REWRITE_RESPONSE_DONE', 'RTSP_REQUEST', 'RTSP_REQUEST_DATA',
    'RTSP_RESPONSE', 'RTSP_RESPONSE_DATA', 'RULE_INIT', 'SERVER_CLOSED', 'SERVER_CONNECTED',
    'SERVER_DATA', 'SERVER_LINE', 'SERVERSSL_CLIENTHELLO_SEND', 'SERVERSSL_DATA', 'SERVERSSL_HANDSHAKE',
    'SERVERSSL_SERVERHELLO', 'SIP_REQUEST', 'SIP_REQUEST_SEND', 'SIP_RESPONSE', 'SIP_RESPONSE_SEND',
    'SOCKS_REQUEST', 'STREAM_MATCHED', 'USER_REQUEST', 'USER_RESPONSE', 'XML_BEGIN_DOCUMENT',
    'XML_BEGIN_ELEMENT', 'XML_CDATA', 'XML_CONTENT_BASED_ROUTING', 'XML_END_DOCUMENT',
    'XML_END_ELEMENT', 'XML_EVENT' ];

    return {
      list: list
    };
  });
});
